[project]

fullname = "Corpus of Resolutions: UN Security Council"
shortname = "CR-UNSC"
author = "Seán Fobbe, Niccolò Ridi and Lorenzo Gasbarri"



[license]

data = "Creative Commons Zero 1.0 Universal"
code = "MIT-0"



[doi] # Digital Object Identifier

data.concept = "???"
data.version = "???" 

software.concept = "123"
software.version = "345" 



[debug]

toggle = false # true/false - whether to activate debuging mode
sample = 50 # integer - number of resolutions to randomly sample



[cores] # Parallelization

max = true # use all cores on system
number = 8 # only used if max = false


[parallel] # Parallelization

extractPDF = true
lingsummarize = true
multihashes = true



[download]

timeout = 600	# Timeout for downloads



[quanteda]

tokens_locale = "en_US"



[fig] # Knitr

fig.format = [ "pdf", "png" ] 	# Output format of figures
fig.dpi = 300     	 	# Resolution of figures
fig.align = "center"    	# Alignment of figures
