[project]

fullname = "Corpus of Resolutions: UN Security Council"
shortname = "CR-UNSC"
author = "Seán Fobbe, Lorenzo Gasbarri and Niccoló Ridi"



[license]

data = "Creative Commons Zero 1.0 Universal"
code = "MIT-0"



[doi] # Digital Object Identifier

data.concept = "10.5281/zenodo.7319780"
data.version = "10.5281/zenodo.7319781" 

software.concept = "10.5281/zenodo.7319783"
software.version = "10.5281/zenodo.7319784" 



[debug]

toggle = false # true/false - whether to activate debuging mode
sample = 100 # integer - number of resolutions to randomly sample

cleanrun = false # Deletes all intermediate and final results before a run. This setting is independent from the debugging toggle!



[cores] # Parallelization

max = true # use all cores on system
number = 8 # only used if max = false
tesseract = 4  # only used if max = false; tesseract uses 3-4 cores per job



[parallel] # Parallelization

extractPDF = true
lingsummarize = true
multihashes = true



[download]

resmax = 2722  # Maximum resolution number to download
timeout = 600	# Timeout for downloads



[quanteda]

tokens_locale = "en_US"



[fig] # Knitr

format = [ "pdf", "png" ] 	# Output format of figures
dpi = 300     	 	# Resolution of figures
align = "center"    	# Alignment of figures
