# This script will delete all data and targets generated by the data set creation process. Use if you wish to do a hard reset for a fresh rerun.

targets::tar_destroy(ask = FALSE)


dir.pdf <- list.files(pattern = "pdf", include.dirs = TRUE)
dir.txt <- list.files(pattern = "txt", include.dirs = TRUE)
dir.record <- list.files(pattern = "record", include.dirs = TRUE)


delete <- c(dir.pdf,
            dir.txt,
            dir.record,
            "temp/",
            "analysis/",
            "output/")



unlink(delete, recursive = TRUE)
