version: "3.7"

services:
  cr-unsc:
    container_name: cr-unsc
    image: cr-unsc:4.2.2
    tty: true
    volumes:
      - .:/cr-unsc:z
      - ./gitconfig:/etc/gitconfig:z
      - ./etc/magick-policy.xml:/etc/ImageMagick-6/policy.xml:z	