version: "3.7"

services:
  cr-unsc:
    container_name: cr-unsc
    image: cr-unsc:4.2.2
    tty: true
    tmpfs: /tmp
    volumes:
      - .:/cr-unsc
      - ./gitconfig:/etc/gitconfig 
      - ./etc/magick-policy.xml:/etc/ImageMagick-6/policy.xml