---
title: "Codebook | Corpus of Resolutions: UN Security Council"
author: "Seán Fobbe, Niccolo Ridi and Lorenzo Gasbarri"
geometry: margin=3cm
papersize: a4
fontsize: 11pt
output:
  pdf_document:
    toc: true
    toc_depth: 3
    number_sections: true
    pandoc_args: --listings
    includes:
      in_header: ../tex/Preamble_EN.tex
      before_body: [../temp/Definitions.tex, ../tex/Titlepage_Codebook.tex]
bibliography: ../temp/packages.bib
nocite: '@*'
---




```{r, setup, include=FALSE}
knitr::opts_chunk$set(fig.path = file.path("..", "analysis/"),
                      dev = config$fig$format,
                      dpi = config$fig$dpi,
                      fig.align = config$fig$align,
                      echo = FALSE,
                      warning = FALSE,
                      message = FALSE)

```


```{r, echo = FALSE}
tar_load(latexdefs)
tar_load(lingstats.summary)

```



# Introduction

Lorem Ipsum.




```{r, CR-UNSC_00_Pipeline_Graph_blackwhite, fig.width = 12, fig.height = 14, fig.pos = "p", fig.cap = "The complete data set compilation process."}


edgelist <- tar_network(targets_only = TRUE)$edges
setDT(edgelist)

g  <- igraph::graph.data.frame(edgelist,
                               directed = TRUE)


ggraph(g,
       'sugiyama') + 
    geom_edge_diagonal(colour = "grey70")+
    geom_node_point(size = 2)+
    geom_node_text(aes(label = name),
                   size = 2,
                   repel = TRUE)+
    theme_void()+
    labs(
        title = paste(prefix.figuretitle,
                      "| Complete data set compilation process."),
        caption = caption
    )+
    theme(
        plot.title = element_text(size = 14,
                                  face = "bold"),
        plot.margin = margin(10, 20, 10, 10)
    )

```






```{r, results = "asis"}
cat(readLines(tar_read(changelog)),
    sep = "\n")

```






# Replication Parameters


```{r}
system2("openssl", "version", stdout = TRUE)

sessionInfo()

```


# Bibliography
