---
title: "Robustness Checks | Corpus of Resolutions: UN Security Council"
author: "Seán Fobbe, Niccolò Ridi and Lorenzo Gasbarri"
geometry: margin=3cm
papersize: a4
fontsize: 11pt
output:
  pdf_document:
    toc: true
    toc_depth: 3
    number_sections: true
    pandoc_args: --listings
    includes:
      in_header: ../tex/Preamble_EN.tex
      before_body: [../temp/Definitions.tex,../tex/Titlepage_Robustness.tex]
bibliography: ../temp/packages.bib
nocite: '@*'
---



```{r, setup, include=FALSE}
knitr::opts_chunk$set(fig.path = file.path("..", "analysis/"),
                      dev = config$fig$format,
                      dpi = config$fig$dpi,
                      fig.align = config$fig$align,
                      echo = TRUE,
                      warning = TRUE,
                      message = TRUE)

```


# Overview

## Load results

```{r}
tar_load(latexdefs)
tar_load(dt.var_codebook)
tar_load(lingstats.summary)
tar_load(dt.record.final)
tar_load(dt.download.final)
tar_load(dt.final)
tar_load(igraph_citations)

```

## Count Automated Tests


```{r}

Rfiles <- list.files("functions", pattern = "\\.R$", full.names = TRUE)
code <- unlist(lapply(Rfiles, readLines))


```


### Tests


```{r}

sum(stringi::stri_count(regex = "test_that\\(", code))

```

### Expectations

```{r}

sum(stringi::stri_count(regex = "expect_", code))

```



# Introduction

Lorem Ipsum. test




# Visualize Pipeline



```{r, CR-UNSC_00_Pipeline_Graph_blue, fig.width = 16, fig.height = 18, fig.pos = "p", fig.cap = "The complete data set compilation process."}


edgelist <- tar_network(targets_only = TRUE)$edges
setDT(edgelist)

g  <- igraph::graph.data.frame(edgelist,
                               directed = TRUE)

ggraph(g,
       'sugiyama') + 
    geom_edge_diagonal(colour = "#55c8ff")+
    geom_node_point(size = 2,
                    color = "white")+
    geom_node_text(aes(label = name),
                   color = "white",
                   size = 2,
                   repel = TRUE)+
    theme_void()+
    labs(
        title = paste(prefix.figuretitle,
                      "| Complete data set compilation process"),
        caption = caption
    )+
    theme(
        plot.title = element_text(size = 14,
                                  face = "bold",
                                  color = "white"),                        
        plot.background = element_rect(fill = "black"),
        plot.caption = element_text(color = "white"),
        plot.margin = margin(10, 20, 10, 10)
    )

```




# Missing Values Check



```{r, results = "asis"}

missingvalues <- f.missingvalues(x = dt.final,
                                 kable = TRUE,
                                 dir.out = dir.analysis,
                                 prefix.files = prefix.files)


```



# Frequency Tables


## Selected Variables

 **Note:** Frequency tables are calculate only for these variables.

```{r}
varnames <- dt.var_codebook[freqtable == 1]$varname
varnames <- gsub("\\\\", "", varnames)
print(varnames)


```




```{r}

## Define prefix

prefix <- paste0(config$project$shortname,
                 "_01_FrequencyTable_var-")

```

## Run Frequency Tables


```{r, results = "asis"}

f.fast.freqtable(dt.final,
                 varlist = varnames,
                 sumrow = TRUE,
                 output.list = FALSE,
                 output.kable = TRUE,
                 output.csv = TRUE,
                 outputdir = dir.analysis,
                 prefix = prefix,
                 align = c("p{5cm}",
                           rep("r", 4)))

```











```{r, results = "asis"}
cat(readLines(tar_read(changelog)),
    sep = "\n")

```






# Replication Parameters


```{r}
system2("openssl", "version", stdout = TRUE)

sessionInfo()

```


# Bibliography
