pkgs <- c("data.table",
          "future",
          "future.apply",
          "targets",
          "tarchetypes",
          "qs",
          "bib2df",
          "RcppTOML",
          "mgsub",
          "readtext",
          "quanteda",
          "quanteda.textstats",
          "quanteda.textplots",
          "spacyr",
          "udpipe",
          "textcat",
          "igraph",
          "ggraph",
          "visNetwork",
          "ggplot2",
          "viridis",
          "RColorBrewer",
          "scales",
          "magick",
          "knitr",
          "kableExtra",
          "pdftools",
          "fs",
          "httr",
          "rvest",
          "renv",
          "testthat",
          "zip")


install.packages(pkgs)
